version: '2.1'
services:

### MySQL Container

  sensehub_db:
      container_name: sensehub_db
      restart: always
      image: sensehub/sensehub_db
      build: ./mysql
      volumes:
          - ./mysql/data:/var/lib/mysql
      env_file:
          - ./.env
          - ./mysql/.env

#  sensehub_cache:
#      container_name: sensehub_cache
#      restart: always
#      image: memcached:alpine

### Application Code Container

  sensehub_application:
      command: >
        bash -c "

        /app/wait-for-it/wait-for-it.sh -h sensehub_db -p 3306 -- python /app/server.py"
      container_name: sensehub_app
      restart: always
      build: ./application
      image: sensehub/sensehub_app
      volumes:
          - ./application:/app
          - .:/source
      env_file:
          - ./.env
          - ./application/.env
      ports:
          - "8000:5000"
      depends_on:
          - sensehub_db
          #- sensehub_cache
